### PR TITLE
[ISSUE-7] Automated import sorting

### LINKED ISSUE #7: Add isort to automatically sort imports
https://pycqa.github.io/isort/

### PR DESCRIPTION
**Pull request by NicolaDonelli**
Closes #7

### CODE REVIEW

**Comment by deusebio** [comment]
Uhm. The makefile is getting overly complicated and I believe we should rather reduce the number of commands, to expose a good minimum set to perform most sensible tasks.

With respect to this PR, i would honestly put the sorting (which I agree with) , together with black. Both are performed in order to adhere to standards

Beside, I really believe we should get rid of install_dev, reinstall and reinstall_dev. I really don't see why we should have 

1. install-reinstall  since when modifying even one line of the package, it should be make that does the reinstalling since something in the dependency chain was modified

2. Dev // no_dev installation. The package does not depend on dev requirements. I don't see why we should have a install dev

**Comment by NicolaDonelli** [comment]
I agree that the Makefile should be made easier and that import sorting and formatting should be joined. Furthermore they should be removed from checks, since they do not actually perform any check.

For what it takes install and reinstall I agree that the logic should be only one: that every time one runs the command the installation process should install the current code. But this could be achieved only by changing the install-tag dynamics since, as of now, install/install_dev do not override the installation if the tar didn't change (i.e. if one didn't commit anything).

Finally, I see a value in distinguishing between install and install_dev since there could be situations in which one wants to install the package only and other in which one wants to install all the dev enviroment.

Since it seems that there should be quite some changes to the Makefile I'd suggest to open a dedicated issue and PR after closing this one.

**Comment by deusebio** [comment]
> Since it seems that there should be quite some changes to the Makefile I'd suggest to open a dedicated issue and PR after closing this one.

I don't think there would be so many changes, honestly. It should really be a matter of few lines (deleting mostly and reviewing) of code

**Comment by deusebio** [comment]
I actually opened a PR (#14 ) with the modification to the Makefile to obtained the expected behaviour I talk about in the replies above

**Review by deusebio — APPROVED** [review]
All good! Just remember to squash the commits into one. I don't think we want to keep both commits

**Pull request merged**
