### PR TITLE
[ISSUE-17] Substitute setup.cfg with pyproject.toml

### LINKED ISSUE #17: Migrate from setup.cfg to pyproject.toml
Since this is the direction taken by many python projects so far (see [setuptools](https://github.com/pypa/setuptools/issues/3214) for example), it could be a good idea to migrate our configuration file from `setup.cfg` to `pyproject.toml`.

[ini2toml](https://ini2toml.readthedocs.io/en/latest/readme.html) could help with this.

### PR DESCRIPTION
**Pull request by NicolaDonelli**
Closes #17

### CODE REVIEW

**Comment by NicolaDonelli** [comment]
@deusebio I cannot replicate on my local the mypy error that breaks the checks, thus I suspect it is due to the unbuntu-latest image... could you please check if on your ubuntu local the `make mypy` command actually works fine or not?

**Comment by deusebio** [comment]
In my local, it works on 3.10 but breaks on 3.9. (Could it be the python version rather than the OS?)

One of the reasons, why we did not switch to TOML is that the landscape was not yet ready a few months ago. Could it be the reason why older versions of python do not seem to work properly? I have not looked into this, just speculating here. But for sure, the failures applied to ubuntu 20.04 (tested in CI) and ubuntu 22.04 (testing in my local)

**Comment by NicolaDonelli** [comment]
It actually could had been a matter of python version, but now it seems I solved it (tweaking a bit the usage of mypy).

**Comment by deusebio** [comment]
Good to go!

**Review by deusebio — DISMISSED** [review]

**Comment by NicolaDonelli** [comment]
Ok, I rebased on the main branch to incorporate changes introduced by PR #7 #9 and #10, please let me know if it is allright or there is something to change before merging on main.

**Comment by deusebio** [comment]
I believe I had already approved

**Review by deusebio — APPROVED** [review]

**Pull request merged**
